version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    ports:
      - 3308:3306 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
